### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ranocha** [ranocha/2023_modeling_matters#1]
- [x] Finish abstract
- [x] Make the repo public
- [x] Register it at Zenodo
- [x] Make a release
- [x] Copy the Zenodo DOI to the README and the reference list of the paper etc.
- [x] Submit the paper
- [x] Link to the preprint
